apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db18c-oracle-db
  namespace: oracle
  labels:
    app: db18c-oracle-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "20Gi"
  storageClassName: "nfs-client"